service: videolyzer

provider:
  name: aws
  runtime: python3.6
  profile: ${file(../config.${self:provider.stage}.json):videolyzer.profile}
  region: us-east-2

  iamRoleStatements: 
    - Effect: "Allow"
      Action: 
        - "rekognition:*"
      Resource: "*"
    - Effect: "Allow"
      Action: 
        - "s3:GetObject"
      Resource:
        - Fn::Join: 
          - ''
          - - ${self:custom.videosBucketArn}
            - '/*'

custom: 
  videosBucketArn: 
      Fn::Join: 
        - ':'
        - - arn
          - aws
          - s3
          - ''
          - ''
          - ${file(../config.${self:provider.stage}.json):videolyzer.videos_bucket}

# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
  startProcessingVideo:
    handler: handler.start_processing_video
    events: 
      - s3: 
          bucket: ${file(../config.${self:provider.stage}.json):videolyzer.videos_bucket}
          event: s3:ObjectCreated:*
          rules: 
            - suffix: .mp4
