service: videolyzer

provider:
  name: aws
  runtime: python3.6
  profile: ${file(../config.${self:provider.stage}.json):videolyzer.profile}
  region: us-east-2

# you can define service wide environment variables here
#  environment:
#    variable1: value1

functions:
  startProcessingVideo:
    handler: handler.start_processing_video
    events: 
      - s3: 
          bucket: ${file(../config.${self:provider.stage}.json):videolyzer.videos_bucket}
          event: s3:ObjectCreated:*
          rules: 
            - suffix: .mp4
